name: pull_request

on: [pull_request]

jobs:
  pull_request:
    uses: MapColonies/shared-workflows/.github/workflows/pull_request.yaml@v4
    secrets: inherit
    with:
      openApiFilePath: './bundledApi.yaml'
